import uuid
import os
from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, Request, UploadFile
from fastapi.responses import JSONResponse
from typing import List, Dict
from src.nlp.doc_handler import DocumentHandler
from src.nlp.embeddings import EmbeddingHandler
from src.nlp.retriever import Retriever
from src.utils.logging import api_logger
from langchain_core.documents import Document

#load environment variables from .env file
load_dotenv()

#initialize FastAPI app
app = FastAPI()

#load the standard ESG documents from the specified directory
standard_docs_dir = os.getenv("STANDARD_DOCS_DIR", "data/standards")
doc_handler = DocumentHandler()
standard_documents = doc_handler.load_standard_documents(standard_docs_dir)

#Placeholder for user uploaded reports
user_uploaded_report = {}

#get the file path for the prompts yaml file
prompts_file_path = os.getenv("PROMPTS_FILE_PATH")

@app.get("/health")
async def health_check():
    """
    Health check endpoint to verify if the API is running smoothly.
    """
    return {"status": "ok", "message": "API is running smoothly."}

@app.post("/upload")
async def upload_documents(files: List[UploadFile] = File(...)):
    """
    Endpoint to handle user uploaded ESG reports for analysis
    """
    try:
        doc_handler = DocumentHandler()
        docs = doc_handler.load_uploaded_documents(files)
        if not docs:
            api_logger.error("No valid documents were uploaded.")
            raise HTTPException(status_code=400, detail="No valid documents were uploaded.")
        session_id = str(uuid.uuid4())
        user_uploaded_report[session_id] = docs
        api_logger.info(f"Successfully processed {len(docs)} documents from upload with session ID {session_id}.")
        return JSONResponse(
            content={
                "status": "success",
                "message": f"Successfully uploaded and processed {len(docs)} documents.",
                "session_id": session_id
            },
            status_code=200
        )
    except Exception as e:
        api_logger.error(f"Error processing uploaded documents: {e}")
        raise HTTPException(status_code=500, detail="Error processing uploaded documents.")



@app.post("/query")
async def query_assistant(request:Request):
    """
    Endpoint to handle user queries and return responses from the AI assistant.
    """
    try:
        data = await request.json()
        query = data.get("query")
        session_id = data.get("session_id")
        
        if not query:
            api_logger.error("No query provided in the request.")
            raise HTTPException(status_code=400, detail="No query provided.")
        
        #retrieve the uploaded reports for the given session ID
        uploaded_reports = user_uploaded_report.get(session_id, [])
        if not uploaded_reports:
            api_logger.error(f"No uploaded reports found for session ID {session_id}.")
            raise HTTPException(status_code=400, detail="No uploaded reports found for the provided session ID.")
        
        #initialize the retriever with embedding handler
        retriever = Retriever(embedding_handler=EmbeddingHandler())

        #create vector stores for standards and uploaded reports
        standard_path = r"C:\Projects_ML\ESG-Report-Analyzer\ESG-Report-Analyzer-NLP\vectorstores\standards"
        reports_path = r"C:\Projects_ML\ESG-Report-Analyzer\ESG-Report-Analyzer-NLP\vectorstores\uploaded_reports"
        retriever.create_vector_store(
            standards_vector_path=standard_path,
            standard_docs=standard_documents,
            uploaded_report=uploaded_reports,
            reports_vector_path= os.path.join(reports_path, f"{session_id}")
        )

        #use the retriever to get the response from the assistant
        response = retriever.compare_content(
            query=query,
            prompts_file=prompts_file_path
        )
        if not response:
            api_logger.error("No response generated by the assistant.")
            raise HTTPException(status_code=500, detail="No response generated by the assistant.")
        api_logger.info(f"Generated response for query: {query}")
        return JSONResponse(
            content={
                "status": "success",
                "response": response
            },
            status_code=200
        )
    except Exception as e:
        api_logger.error(f"Error processing query: {e}")
        raise HTTPException(status_code=500, detail="Error processing query.")



@app.post("/predict_esg_score")
async def predict_esg_score(request: Request):
    pass

# @app.post("/forecast_esg_trends")
# async def forecast_esg_trends():
#     pass